import { VerticalBox, HorizontalBox, LineEdit, Button, CheckBox, StandardButton } from "std-widgets.slint";

Main := Window {
  preferred-width: 380px;
  preferred-height: 220px;
  title: "Electron icon builder";
  icon: @image-url("./logo.png");

  property <string> inputPath: "";
  property <string> outputPath: "";
  property <bool> flatten: false;
  property <string> popupText: "";

  callback handleInput;
  callback handleOutput;
  callback handleConfirm(string, string, bool);
  callback handleReset;

  callback show_popup;
  show_popup => { popup.show(); }
  popup := PopupWindow {
    width: 300px;
    x: 40px;
    y: 40px;
    Rectangle {
      background: root.background;
      border-width: 1px;
      border-color: #000000;
    }
    popup_layout := Dialog {
      height: 100%;
      width: 100%;
      popup_text := Text {
        text <=> popupText;
        wrap: word-wrap;
        color: red;
      }
      StandardButton { kind: yes; }
    }
  }

  VerticalBox {
    HorizontalBox {
      input := LineEdit {
        height: 32px;
        placeholder-text: "./icon.png";
        text <=> inputPath;
      }
      inputBtn := Button {
        text: "Input";
        clicked => { handleInput(); }
      }
    }
    HorizontalBox {
      output := LineEdit {
        height: 32px;
        placeholder-text: "./build/";
        text <=> outputPath;
      }
      outputBtn := Button {
        text: "Output";
        clicked => { handleOutput(); }
      }
    }
    HorizontalBox {
      flag := CheckBox {
        checked <=> flatten;
        text: "Flatten";
      }
      reset := Button {
        height: 32px;
        text: "Reset";
        clicked => { handleReset(); }
      }
      confirm := Button {
        text: "Confirm";
        clicked => { handleConfirm(input.text, output.text, flatten); }
      }
    }
  }
}